version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "gameparty"
  web:
    build: ../api
    ports:
      - "8000:8000"
    depends_on:
      - db
  # frontend:
  #   build: ../frontend
