# Generated by Django 4.1.2 on 2022-10-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('contest_id', models.CharField(max_length=127)),
                ('problem_index', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=127)),
                ('point', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('fixed_revenue', models.PositiveBigIntegerField()),
                ('bonus_per_time', models.PositiveBigIntegerField()),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('clear_time', models.TimeField()),
                ('revenue_received', models.BooleanField(default=False)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
