version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "beagreatcoder"
  web:
    build: ../api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../api:/code
    entrypoint: /code/entrypoint.sh
  vue:
    build: ../frontend
    volumes:
      - ../frontend:/code
    ports:
      - "5173:5173"
      - "8000:8000"
